export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const DISPLAY_NOTITFICATION_DRAWER = 'DISPLAY_NOTITFICATION_DRAWER';
export const HIDE_NOTITFICATION_DRAWER = 'HIDE_NOTITFICATION_DRAWER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';