export const MARK_AS_READ = 'MARK_AS_READ';
export const SET_TYPE_FILTER = 'SET_TYPE_FILTER';
export const NOTIFICATION_ACTION_FILTERS = {
    DEFAULT: 'DEFAULT',
    URGENT: 'URGENT'
};
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';